name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get tag name
      id: tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Zip project
      run: |
        zip -r "${{ steps.tag.outputs.TAG_NAME }}.zip" . \
          -x ".git/*" "*.zip" ".github/*"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        name: Release ${{ steps.tag.outputs.TAG_NAME }}
        body: |
          release： ${{ steps.tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false
        files: ${{ steps.tag.outputs.TAG_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
